# Don't touch this file unless you know what you're doing
# Default values seems vanilla.
# If you find values that seems more vanilla please create a PR
# https://github.com/Hynse/FoliaFlow

# Optimize value for horizontal_coefficient
#  - Folia (1.499)
#  - Paper (1.3)
horizontal_coefficient: 1.3
vertical_coefficient: -1.7
spawn_height: 0.08
teleport_offset: 0.5
