# Don't touch this file unless you know what you're doing
# Default values seems vanilla.
# If you find values that seems more vanilla please create a PR
# https://github.com/Hynse/FoliaFlow

# Default value for horizontal_coefficient
#  - Folia (1.499)
#  - Paper (2)
horizontal_coefficient: 2
# -----------------------------------------

vertical_coefficient: -1.7
spawn_height: 0.08

# Default value for teleport_offset
#  - Folia (0.5)
#  - Paper (2.4)
teleport_offset: 2.4
# -----------------------------------------